// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"time"
)

type Period struct {
	ID            int32     `json:"id"`
	CompetitionID int32     `json:"competition_id"`
	EndTime       time.Time `json:"end_time"`
	RoundID       int64     `json:"round_id"`
	StartTime     time.Time `json:"start_time"`
}
