// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: rounds.sql

package db

import (
	"context"
	"time"
)

const createPeriod = `-- name: CreatePeriod :one
INSERT INTO periods (
  competition_id,
  end_time,
  round_id,
  start_time
) VALUES(
    $1, $2, $3, $4
) RETURNING id, competition_id, end_time, round_id, start_time
`

type CreatePeriodParams struct {
	CompetitionID int32     `json:"competition_id"`
	EndTime       time.Time `json:"end_time"`
	RoundID       int64     `json:"round_id"`
	StartTime     time.Time `json:"start_time"`
}

func (q *Queries) CreatePeriod(ctx context.Context, arg CreatePeriodParams) (Period, error) {
	row := q.db.QueryRowContext(ctx, createPeriod,
		arg.CompetitionID,
		arg.EndTime,
		arg.RoundID,
		arg.StartTime,
	)
	var i Period
	err := row.Scan(
		&i.ID,
		&i.CompetitionID,
		&i.EndTime,
		&i.RoundID,
		&i.StartTime,
	)
	return i, err
}
